import os
import sys
import django

sys.path.insert(0, os.path.dirname(__file__))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'python.settings')
django.setup()

from productos.models import Producto

productos_data = [
    # Procesadores
    {
        'nombre': 'AMD Ryzen 9 7950X',
        'descripcion': '16 núcleos, 32 hilos, 5.7GHz Max Boost. El procesador más potente para gaming y creación de contenido.',
        'precio': 549.99,
        'precio_original': 699.99,
        'imagen': 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=400&h=400&fit=crop&q=80',
        'cantidad': 25,
        'categoria': 'procesadores',
        'rating': 9.4,
        'badge': 'Oferta',
        'destacado': True,
        'en_oferta': True,
    },
    {
        'nombre': 'Intel Core i9-14900K',
        'descripcion': '24 núcleos (8P+16E), 32 hilos, hasta 6.0GHz. Rendimiento extremo para multitarea.',
        'precio': 589.99,
        'imagen': 'https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=400&h=400&fit=crop&q=80',
        'cantidad': 18,
        'categoria': 'procesadores',
        'rating': 9.2,
        'badge': 'Popular',
        'destacado': True,
        'en_oferta': False,
    },
    {
        'nombre': 'AMD Ryzen 7 7800X3D',
        'descripcion': '8 núcleos, 16 hilos, 3D V-Cache de 96MB. El mejor procesador para gaming.',
        'precio': 399.99,
        'precio_original': 449.99,
        'imagen': 'https://images.unsplash.com/photo-1592664474505-51c582846d81?w=400&h=400&fit=crop&q=80',
        'cantidad': 30,
        'categoria': 'procesadores',
        'rating': 9.6,
        'badge': 'Top Gaming',
        'destacado': True,
        'en_oferta': True,
    },
    # Tarjetas Gráficas
    {
        'nombre': 'NVIDIA RTX 4080 Super',
        'descripcion': '16GB GDDR6X, Ray Tracing, DLSS 3.5. Rendimiento premium para 4K gaming.',
        'precio': 999.99,
        'imagen': 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=400&h=400&fit=crop&q=80',
        'cantidad': 12,
        'categoria': 'tarjetas_graficas',
        'rating': 9.8,
        'badge': 'Popular',
        'destacado': True,
        'en_oferta': False,
    },
    {
        'nombre': 'NVIDIA RTX 4070 Ti Super',
        'descripcion': '16GB GDDR6X, Ray Tracing, DLSS 3.5. La mejor relación rendimiento/precio.',
        'precio': 799.99,
        'precio_original': 899.99,
        'imagen': 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=400&h=400&fit=crop&q=80',
        'cantidad': 20,
        'categoria': 'tarjetas_graficas',
        'rating': 9.3,
        'badge': 'Oferta',
        'destacado': True,
        'en_oferta': True,
    },
    {
        'nombre': 'AMD Radeon RX 7900 XTX',
        'descripcion': '24GB GDDR6, Arquitectura RDNA 3, rendimiento excepcional en 4K.',
        'precio': 899.99,
        'imagen': 'https://images.unsplash.com/photo-1625225233840-695456021cde?w=400&h=400&fit=crop&q=80',
        'cantidad': 8,
        'categoria': 'tarjetas_graficas',
        'rating': 9.0,
        'badge': '',
        'destacado': False,
        'en_oferta': False,
    },
    # RAM
    {
        'nombre': 'Corsair Vengeance RGB 64GB',
        'descripcion': 'DDR5 6000MHz, CL30, Kit de 2x32GB. Iluminación RGB dinámica.',
        'precio': 279.99,
        'imagen': 'https://images.unsplash.com/photo-1562976540-1502c2145186?w=400&h=400&fit=crop&q=80',
        'cantidad': 40,
        'categoria': 'ram',
        'rating': 8.5,
        'badge': '',
        'destacado': True,
        'en_oferta': False,
    },
    {
        'nombre': 'G.Skill Trident Z5 RGB 32GB',
        'descripcion': 'DDR5 6400MHz, CL32, Kit de 2x16GB. Diseño premium con RGB.',
        'precio': 169.99,
        'precio_original': 199.99,
        'imagen': 'https://images.unsplash.com/photo-1541029071515-84cc54f84dc5?w=400&h=400&fit=crop&q=80',
        'cantidad': 55,
        'categoria': 'ram',
        'rating': 8.8,
        'badge': 'Oferta',
        'destacado': False,
        'en_oferta': True,
    },
    # Almacenamiento
    {
        'nombre': 'Samsung 990 Pro 2TB',
        'descripcion': 'NVMe M.2, 7450MB/s lectura, con disipador integrado.',
        'precio': 189.99,
        'precio_original': 229.99,
        'imagen': 'https://images.unsplash.com/photo-1597138804456-e7dca7f59d54?w=400&h=400&fit=crop&q=80',
        'cantidad': 35,
        'categoria': 'almacenamiento',
        'rating': 9.1,
        'badge': 'Nuevo',
        'destacado': True,
        'en_oferta': True,
    },
    {
        'nombre': 'WD Black SN850X 1TB',
        'descripcion': 'NVMe M.2 Gen4, 7300MB/s, diseñado para gaming.',
        'precio': 109.99,
        'imagen': 'https://images.unsplash.com/photo-1628557044797-f21d05e58033?w=400&h=400&fit=crop&q=80',
        'cantidad': 50,
        'categoria': 'almacenamiento',
        'rating': 8.7,
        'badge': '',
        'destacado': False,
        'en_oferta': False,
    },
    # Monitores
    {
        'nombre': 'ASUS ROG Swift 27" 4K',
        'descripcion': '144Hz, 1ms, HDR600, G-Sync Compatible. Panel IPS premium.',
        'precio': 799.99,
        'precio_original': 899.99,
        'imagen': 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=400&fit=crop&q=80',
        'cantidad': 10,
        'categoria': 'monitores',
        'rating': 9.5,
        'badge': 'Oferta',
        'destacado': True,
        'en_oferta': True,
    },
    {
        'nombre': 'Samsung Odyssey G9 49"',
        'descripcion': 'Curvo DQHD 240Hz, 1ms, HDR1000. La experiencia gaming más inmersiva.',
        'precio': 1299.99,
        'imagen': 'https://images.unsplash.com/photo-1616763355548-1b11cea010cf?w=400&h=400&fit=crop&q=80',
        'cantidad': 5,
        'categoria': 'monitores',
        'rating': 9.3,
        'badge': 'Premium',
        'destacado': False,
        'en_oferta': False,
    },
    # Mouse
    {
        'nombre': 'Logitech G Pro X Superlight',
        'descripcion': 'Mouse inalámbrico, 25K DPI, 63g ultraligero. El favorito de los pros.',
        'precio': 149.99,
        'imagen': 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=400&h=400&fit=crop&q=80',
        'cantidad': 60,
        'categoria': 'mouse',
        'rating': 9.2,
        'badge': 'Top Ventas',
        'destacado': True,
        'en_oferta': False,
    },
    {
        'nombre': 'Razer DeathAdder V3 Pro',
        'descripcion': 'Inalámbrico, 30K DPI, 63g, sensor Focus Pro 30K.',
        'precio': 129.99,
        'precio_original': 159.99,
        'imagen': 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=400&h=400&fit=crop&q=80',
        'cantidad': 45,
        'categoria': 'mouse',
        'rating': 9.0,
        'badge': 'Oferta',
        'destacado': False,
        'en_oferta': True,
    },
    # Teclados
    {
        'nombre': 'Corsair K100 RGB',
        'descripcion': 'Teclado mecánico, OPX switches, PBT keycaps, iCUE control.',
        'precio': 229.99,
        'imagen': 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400&h=400&fit=crop&q=80',
        'cantidad': 30,
        'categoria': 'teclados',
        'rating': 8.9,
        'badge': '',
        'destacado': True,
        'en_oferta': False,
    },
    {
        'nombre': 'Razer Huntsman V3 Pro',
        'descripcion': 'Switches ópticos analógicos, PBT keycaps, polling rate de 8000Hz.',
        'precio': 249.99,
        'precio_original': 279.99,
        'imagen': 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&h=400&fit=crop&q=80',
        'cantidad': 22,
        'categoria': 'teclados',
        'rating': 9.1,
        'badge': 'Nuevo',
        'destacado': False,
        'en_oferta': True,
    },
    # Auriculares
    {
        'nombre': 'SteelSeries Arctis Nova Pro',
        'descripcion': 'Auriculares inalámbricos, ANC, audio Hi-Res, batería dual.',
        'precio': 349.99,
        'imagen': 'https://images.unsplash.com/photo-1599669454699-248893623440?w=400&h=400&fit=crop&q=80',
        'cantidad': 15,
        'categoria': 'auriculares',
        'rating': 9.4,
        'badge': 'Premium',
        'destacado': True,
        'en_oferta': False,
    },
    {
        'nombre': 'HyperX Cloud III Wireless',
        'descripcion': 'Inalámbricos, DTS Headphone:X, 120h batería, micrófono desmontable.',
        'precio': 149.99,
        'precio_original': 179.99,
        'imagen': 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=400&h=400&fit=crop&q=80',
        'cantidad': 38,
        'categoria': 'auriculares',
        'rating': 8.6,
        'badge': 'Oferta',
        'destacado': False,
        'en_oferta': True,
    },
    # Ventiladores / Coolers
    {
        'nombre': 'be quiet! Dark Rock Pro 5',
        'descripcion': 'Disipador CPU, 270W TDP, Silent Wings 3, ultra silencioso.',
        'precio': 89.99,
        'precio_original': 109.99,
        'imagen': 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=400&h=400&fit=crop&q=80',
        'cantidad': 28,
        'categoria': 'ventiladores',
        'rating': 9.0,
        'badge': 'Recomendado',
        'destacado': True,
        'en_oferta': True,
    },
    # Chasis
    {
        'nombre': 'NZXT H7 Flow',
        'descripcion': 'Torre mid, flujo de aire optimizado, panel de vidrio templado, gestión de cables.',
        'precio': 129.99,
        'imagen': 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=400&h=400&fit=crop&q=80',
        'cantidad': 20,
        'categoria': 'chasis',
        'rating': 8.8,
        'badge': 'Popular',
        'destacado': False,
        'en_oferta': False,
    },
]

# Limpiar productos existentes
Producto.objects.all().delete()

for data in productos_data:
    Producto.objects.create(**data)

print(f'✅ Se crearon {len(productos_data)} productos exitosamente.')
