# Generated by Django 6.0.4 on 2026-04-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_original', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.URLField(max_length=500)),
                ('cantidad', models.IntegerField(default=0)),
                ('categoria', models.CharField(choices=[('procesadores', 'Procesadores'), ('tarjetas_graficas', 'Tarjetas Gráficas'), ('ram', 'Memoria RAM'), ('almacenamiento', 'Almacenamiento'), ('monitores', 'Monitores'), ('teclados', 'Teclados'), ('mouse', 'Mouse'), ('auriculares', 'Auriculares'), ('chasis', 'Chasis'), ('ventiladores', 'Ventiladores'), ('gamepads', 'Gamepads'), ('fuentes', 'Fuentes de Poder'), ('motherboards', 'Motherboards')], default='procesadores', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('badge', models.CharField(blank=True, default='', max_length=50)),
                ('destacado', models.BooleanField(default=False)),
                ('en_oferta', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
