# Generated by Django 6.0.4 on 2026-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_carrusel',
            field=models.BooleanField(default=False),
        ),
    ]
